# Generated by Django 4.1.4 on 2022-12-27 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="sold_by",
        ),
    ]
