# Generated by Django 4.1.4 on 2022-12-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timeModified",
                    models.DateTimeField(auto_created=True, auto_now_add=True),
                ),
                ("title", models.CharField(max_length=150)),
                ("body", models.TextField()),
                ("read", models.BooleanField(default=False)),
            ],
        ),
    ]
