# Generated by Django 4.1.4 on 2023-01-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.FloatField()),
                ("quantity", models.IntegerField()),
                ("minQuantity", models.IntegerField()),
                ("type", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="products")),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
                "ordering": ("name",),
            },
        ),
    ]
