# Generated by Django 4.1.4 on 2022-12-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_created=True)),
                ("name", models.CharField(max_length=100)),
                ("price", models.FloatField()),
                ("quantity", models.IntegerField()),
                ("minQuantity", models.IntegerField()),
                ("image", models.TextField()),
                ("type", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
                "ordering": ("name",),
            },
        ),
    ]
